# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-07 00:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentuser',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='账号'),
        ),
        migrations.AlterField(
            model_name='agentuser',
            name='name',
            field=models.CharField(max_length=100, verbose_name='代理人名字'),
        ),
    ]
