# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-07 20:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agent', '0004_recharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRecharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='充值金额')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='充值时间')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作人员')),
            ],
        ),
        migrations.AddField(
            model_name='agentuser',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='余额'),
        ),
        migrations.AddField(
            model_name='agentrecharge',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.AgentUser', verbose_name='代理人'),
        ),
    ]
