# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-07 20:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_auto_20201107_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentrecharge',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作人员'),
        ),
    ]
