# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-07 23:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_auto_20201107_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acount', models.CharField(max_length=100, verbose_name='玩家账号')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.AgentUser', verbose_name='代理人')),
            ],
        ),
        migrations.AlterField(
            model_name='agentrecharge',
            name='amount',
            field=models.IntegerField(verbose_name='充值金额'),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.GamePlayer', verbose_name='玩家'),
        ),
    ]
