# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-08 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0008_auto_20201108_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameblock',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.Game', verbose_name='游戏'),
        ),
    ]
