# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-09 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0009_gameblock_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbCharacter',
            fields=[
                ('pc_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=32)),
                ('grade', models.SmallIntegerField()),
                ('pc_name', models.CharField(max_length=24)),
                ('race', models.SmallIntegerField()),
                ('gender', models.SmallIntegerField()),
                ('class_field', models.SmallIntegerField(db_column='class')),
                ('hair_id', models.CharField(max_length=8)),
                ('face_id', models.CharField(max_length=8)),
                ('tail_id', models.CharField(max_length=8)),
                ('pc_level', models.IntegerField()),
                ('pc_exp', models.BigIntegerField()),
                ('hongmoon_level', models.IntegerField()),
                ('hongmoon_exp', models.BigIntegerField()),
                ('pc_hp', models.IntegerField()),
                ('pc_mana', models.IntegerField()),
                ('pc_ability_hp', models.IntegerField(blank=True, null=True)),
                ('pc_hosin_hp', models.IntegerField()),
                ('pc_ability_power', models.FloatField()),
                ('pc_ability_power_max', models.FloatField()),
                ('hongmoon_attack', models.IntegerField()),
                ('hongmoon_defence', models.IntegerField()),
                ('login_time', models.BigIntegerField()),
                ('logout_time', models.BigIntegerField()),
                ('create_time', models.BigIntegerField()),
                ('update_time', models.BigIntegerField()),
                ('changename_time', models.BigIntegerField()),
                ('changebody_time', models.BigIntegerField()),
                ('delete_flag', models.BooleanField()),
                ('delete_time', models.BigIntegerField()),
                ('migration_flag', models.BooleanField()),
                ('migration_step', models.SmallIntegerField()),
                ('locker_flag', models.BooleanField()),
                ('locker_takeout_time', models.BigIntegerField()),
                ('grade_time', models.BigIntegerField()),
                ('total_play_time', models.BigIntegerField()),
                ('today_play_time', models.BigIntegerField()),
                ('user_type', models.SmallIntegerField()),
                ('user_type_expire_time', models.BigIntegerField()),
                ('dw_update_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'tb_character',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='recharge',
            name='charactar',
            field=models.CharField(blank=True, max_length=100, verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='recharge',
            name='pc_id',
            field=models.BigIntegerField(default=0, verbose_name='角色id'),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='status',
            field=models.IntegerField(default=1, verbose_name='状态'),
        ),
    ]
