# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-11 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0010_auto_20201109_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentuser',
            name='regist_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='注册码'),
        ),
    ]
