# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-11 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0011_agentuser_regist_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentuser',
            name='qq',
            field=models.CharField(blank=True, max_length=20, verbose_name='QQ号码'),
        ),
    ]
