# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-12 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0012_agentuser_qq'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='new_guy_gift',
            field=models.BooleanField(default=False, verbose_name='领取新人福利'),
        ),
    ]
