# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-13 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0014_auto_20201112_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='has_get',
            field=models.CharField(blank=True, max_length=200, verbose_name='已领取'),
        ),
    ]
