# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-20 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0015_gameplayer_has_get'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
    ]
