# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-20 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0016_gameplayer_createtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='desp',
            field=models.CharField(blank=True, max_length=300, verbose_name='备注'),
        ),
    ]
