# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-20 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0017_gameplayer_desp'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='history_credit',
            field=models.IntegerField(default=0, verbose_name='历史积分'),
        ),
    ]
