# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-01-03 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0020_auto_20210103_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='block',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agent.GameBlock', verbose_name='分区'),
        ),
    ]
