# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-01-15 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0021_gameplayer_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='EverdaySign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.GamePlayer', verbose_name='玩家')),
            ],
        ),
        migrations.AlterField(
            model_name='storerecord',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.GamePlayer', verbose_name='玩家'),
        ),
    ]
