# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-01-23 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0022_auto_20210115_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.GamePlayer', verbose_name='上级玩家'),
        ),
    ]
