# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-01-23 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0023_gameplayer_par'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargeBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='数量')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='充值时间')),
                ('palyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.GamePlayer', verbose_name='玩家')),
                ('recharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.Recharge', verbose_name='触发充值记录')),
            ],
        ),
    ]
