# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-01-24 01:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0024_rechargebonus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rechargebonus',
            old_name='palyer',
            new_name='player',
        ),
    ]
