# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-01-24 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0025_auto_20210124_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='last_settle_date',
            field=models.DateField(blank=True, null=True, verbose_name='上次结算'),
        ),
    ]
