# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-01-24 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0026_gameplayer_last_settle_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='everdaysign',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='奖励积分'),
        ),
        migrations.AddField(
            model_name='everdaysign',
            name='memo',
            field=models.CharField(blank=True, max_length=200, verbose_name='备注'),
        ),
    ]
